# region IMPORTS
from datetime import datetime, timedelta
# endregion

# region ============= CONTROLE DE CARGA =============

CARGA_FULL = True
BLING_FULL_INICIO=datetime(2023,1,1)
BLING_FULL_FIM=datetime(2023,5,31)

DATA_FULL_INICIAL = datetime(2020, 1, 1)
MARGEM_DIAS_INCREMENTO = 1

RODAR_EMPRESA = True
RODAR_CATEGORIA = True
RODAR_GRUPO_PRODUTO = True
RODAR_PRODUTO = True
RODAR_CANAIS_VENDA = True
RODAR_VENDEDOR = True
RODAR_DEPOSITOS = True
RODAR_SALDO_PRODUTO_DEPOSITO = True
RODAR_PEDIDOS_VENDAS = True
RODAR_CATEGORIAS_RECEITAS_DESPESAS = True
RODAR_CONTATO = True
REPROCESSAR_CONTATO_MANUAL=True


# endregion

# region ============= CONTROLE DE REPROCESSAMENTO =============

REPROCESSAR_FULL = False #(ainda nao implementado)
REPROCESSAR_PRODUTO_MANUAL = True
REPROCESSAR_EMPRESA_MANUAL = True
REPROCESSAR_SALDO_MANUAL = True
REPROCESSAR_PEDIDOS_VENDAS_MANUAL = True


# endregion

# region ============= DEBUGAR =============

DEBUG = True

# endregion